/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_constructor.newService;

import hvv_constructor.newService.PnlServSound.MyWavFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author yaroslav
 */
public class PnlServMessage extends javax.swing.JPanel {

    /**
     * Inner class for FileOpen dialog filter
     */
    class MyWavFilter extends FileFilter {

        @Override
        public boolean accept( File f) {
            if (f.isDirectory()) {
                return true;
            }
            
            String extension = Utils.getExtension( f);
            if( extension != null) {
                if( extension.equals( Utils.wav))
                    return true;
                else
                    return false;
            }

            return false;
        }

        @Override
        public String getDescription() {
            return "WAV files";
        }
        
    }
    
    
    /**
     * Creates new form pnlServMessage
     */
    public PnlServMessage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtMessage = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        edtWavSound = new javax.swing.JTextField();
        btnBrowseWavPeriodic = new javax.swing.JButton();
        edtWavPeriodic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBrowseWavSound = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        edtPeriod = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("<html><u>Текст сообщения:</u><html>");
        add(jLabel1);
        jLabel1.setBounds(30, 50, 830, 30);

        edtMessage.setColumns(20);
        edtMessage.setRows(5);
        jScrollPane1.setViewportView(edtMessage);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 840, 170);

        jLabel2.setText("Звуковой сигнал:");
        add(jLabel2);
        jLabel2.setBounds(30, 10, 120, 30);

        edtWavSound.setEnabled(false);
        add(edtWavSound);
        edtWavSound.setBounds(150, 10, 630, 30);

        btnBrowseWavPeriodic.setText("Обзор");
        btnBrowseWavPeriodic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseWavPeriodicActionPerformed(evt);
            }
        });
        add(btnBrowseWavPeriodic);
        btnBrowseWavPeriodic.setBounds(790, 280, 80, 30);

        edtWavPeriodic.setEnabled(false);
        add(edtWavPeriodic);
        edtWavPeriodic.setBounds(240, 280, 540, 30);

        jLabel3.setText("Перидический зуковой сигнал:");
        add(jLabel3);
        jLabel3.setBounds(30, 280, 210, 30);

        btnBrowseWavSound.setText("Обзор");
        btnBrowseWavSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseWavSoundActionPerformed(evt);
            }
        });
        add(btnBrowseWavSound);
        btnBrowseWavSound.setBounds(790, 10, 80, 30);

        jLabel4.setText("Период (сек):");
        add(jLabel4);
        jLabel4.setBounds(130, 320, 110, 30);
        add(edtPeriod);
        edtPeriod.setBounds(240, 320, 60, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseWavSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseWavSoundActionPerformed
        //Create a file chooser
        final JFileChooser fc = new JFileChooser();
        
        fc.setCurrentDirectory( new File("/home/yaroslav/media"));
        
        fc.setFileFilter( new MyWavFilter());
        
        int returnVal = fc.showOpenDialog( this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            /*
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            log.append("Opening: " + file.getName() + "." + newline);
            */
            File file = fc.getSelectedFile();
            edtWavSound.setText( file.getAbsolutePath());
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_btnBrowseWavSoundActionPerformed

    private void btnBrowseWavPeriodicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseWavPeriodicActionPerformed
        //Create a file chooser
        final JFileChooser fc = new JFileChooser();
        
        fc.setCurrentDirectory( new File("/home/yaroslav/media"));
        
        fc.setFileFilter( new MyWavFilter());
        
        int returnVal = fc.showOpenDialog( this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            /*
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            log.append("Opening: " + file.getName() + "." + newline);
            */
            File file = fc.getSelectedFile();
            edtWavPeriodic.setText( file.getAbsolutePath());
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_btnBrowseWavPeriodicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseWavPeriodic;
    private javax.swing.JButton btnBrowseWavSound;
    public javax.swing.JTextArea edtMessage;
    public javax.swing.JTextField edtPeriod;
    public javax.swing.JTextField edtWavPeriodic;
    public javax.swing.JTextField edtWavSound;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
