/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_constructor.newService;

/**
 *
 * @author yaroslav
 */
public class PnlServAdminStep extends javax.swing.JPanel {

    /**
     * Creates new form pnlServPause
     */
    public PnlServAdminStep() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbSteps = new javax.swing.JComboBox();

        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("<html><u>Отправить в административный модуль сообщение о завершении этапа</u><html>");
        add(jLabel1);
        jLabel1.setBounds(30, 30, 830, 30);

        cmbSteps.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1.1 Заполнение рабочей камеры азотом", "2.2 Предварительная откачка", "2.3.1 Напуск азота", "2.4 Основная откачка", "3.1 Напуск кислорода в приборы", "3.2 Обработка. 1ый цикл.", "3.3 Откачка кислорода", "3.4 Напуск кислорода в приборы", "3.5 Обработка. 2ой цикл.", "3.6 Откачка кислорода", "4.1 Напуск кислород-неона в приборы", "4.2 Обработка. 1ый цикл.", "4.3 Откачка газовой смеси", "4.4 Напуск кислород-неона в приборы", "4.5 Обработка. 2ой цикл.", "4.6 Откачка газовой смеси", "4.7 Переход на основную откачку", "5.2.1 Открытие геттера", "5.4 Заполнение рабочей смесью", "5.5 Выдержка", "6.4 Откачка рабочей смеси", "7.1 Напуск тренировочной смеси в приборы", "7.2 Выдержка", "7.3 Обработка. 1ый цикл.", "7.4 Откачка тренировочной смеси", "7.5 Напуск тренировочной смеси в приборы", "7.6 Выдержка", "7.7 Обработка. 2ой цикл.", "7.8 Откачка тренировочной смеси", "7.9 Напуск тренировочной смеси в приборы", "7.10 Выдержка", "7.11 Обработка. 3ий цикл.", "7.12 Откачка тренировочной смеси", "7.13 Переход на основную откачку", "8.2 Открытие геттера", "9.1 Напуск тренировочной смеси в приборы", "9.2 Выдержка", "9.3 Обработка. 1ый цикл.", "9.4 Откачка тренировочной смеси", "9.5 Напуск тренировочной смеси в приборы", "9.6 Выдержка", "9.7 Обработка. 2ой цикл.", "9.8 Откачка тренировочной смеси", "9.9 Переход на основную откачку ", "10.2 Открытие геттера", "11.1 Заполнение рабочей смесью", "11.2 Выдержка", "12.1 Закрытие геттера", "12.2 Напуск азота в приборы", "13.1 Bypass-откачка", "13.2.1 Напуск азота", "13.3 Основная откачка", "13.4 Откачка смеси с геттера" }));
        add(cmbSteps);
        cmbSteps.setBounds(30, 70, 830, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cmbSteps;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
