/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_constructor.newService;

import org.apache.log4j.Logger;


/**
 *
 * @author yaroslav
 */
public class PnlServPause extends javax.swing.JPanel {

    static Logger logger = Logger.getLogger( PnlServPause.class);
    
    long m_lPauseMillis;
    
    /**
     * Creates new form pnlServPause
     */
    public PnlServPause() {
        initComponents();
        m_lPauseMillis = 1000;
    }

    public void ActualizeFields() {
        if( m_lPauseMillis < 100)
            m_lPauseMillis = 100;
        edtDuration.setText( "" + m_lPauseMillis);
        
        long nHours = m_lPauseMillis / 3600000;
        long nMinutes = ( m_lPauseMillis % 3600000) / 60000;
        long nSeconds = (( m_lPauseMillis % 3600000) % 60000) / 1000;
        long nMillis = m_lPauseMillis % 1000;
        
        lblHours.setText(    String.format( "%02d", nHours));
        lblMinutes.setText(  String.format( "%02d", nMinutes));
        lblSeconds.setText(  String.format( "%02d", nSeconds));
        lblMseconds.setText( String.format( "%03d", nMillis));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edtDuration = new javax.swing.JTextField();
        lblMseconds = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMinutes = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblHours = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblSeconds = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("<html><u>Длительность, мсек</u><html>");
        add(jLabel1);
        jLabel1.setBounds(30, 30, 830, 30);

        edtDuration.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edtDuration.setText("1000");
        edtDuration.setToolTipText("");
        edtDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDurationActionPerformed(evt);
            }
        });
        add(edtDuration);
        edtDuration.setBounds(30, 70, 210, 40);

        lblMseconds.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblMseconds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMseconds.setText("999");
        lblMseconds.setBorder(null);
        lblMseconds.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblMsecondsMouseWheelMoved(evt);
            }
        });
        add(lblMseconds);
        lblMseconds.setBounds(280, 150, 90, 50);

        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(".");
        jLabel5.setBorder(null);
        add(jLabel5);
        jLabel5.setBounds(260, 150, 20, 50);

        lblMinutes.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblMinutes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinutes.setText("59");
        lblMinutes.setBorder(null);
        lblMinutes.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblMinutesMouseWheelMoved(evt);
            }
        });
        add(lblMinutes);
        lblMinutes.setBounds(140, 150, 50, 50);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("миллисекунд");
        add(jLabel7);
        jLabel7.setBounds(280, 120, 90, 20);

        lblHours.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblHours.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHours.setText("23");
        lblHours.setBorder(null);
        lblHours.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblHoursMouseWheelMoved(evt);
            }
        });
        add(lblHours);
        lblHours.setBounds(30, 150, 90, 50);

        jLabel10.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(":");
        jLabel10.setBorder(null);
        add(jLabel10);
        jLabel10.setBounds(120, 150, 20, 50);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("часов");
        add(jLabel11);
        jLabel11.setBounds(50, 120, 70, 20);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("минут");
        add(jLabel12);
        jLabel12.setBounds(140, 120, 48, 20);

        jLabel13.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(":");
        jLabel13.setBorder(null);
        add(jLabel13);
        jLabel13.setBounds(190, 150, 20, 50);

        lblSeconds.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblSeconds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeconds.setText("59");
        lblSeconds.setBorder(null);
        lblSeconds.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblSecondsMouseWheelMoved(evt);
            }
        });
        add(lblSeconds);
        lblSeconds.setBounds(210, 150, 50, 50);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("секунд");
        add(jLabel14);
        jLabel14.setBounds(210, 120, 48, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHoursMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblHoursMouseWheelMoved
        m_lPauseMillis -= evt.getWheelRotation() * 3600000;
        ActualizeFields();
    }//GEN-LAST:event_lblHoursMouseWheelMoved

    private void lblMinutesMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblMinutesMouseWheelMoved
        m_lPauseMillis -= evt.getWheelRotation() * 60000;
        ActualizeFields();
    }//GEN-LAST:event_lblMinutesMouseWheelMoved

    private void lblSecondsMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblSecondsMouseWheelMoved
        m_lPauseMillis -= evt.getWheelRotation() * 1000;
        ActualizeFields();
    }//GEN-LAST:event_lblSecondsMouseWheelMoved

    private void lblMsecondsMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblMsecondsMouseWheelMoved
        m_lPauseMillis -= evt.getWheelRotation() * 100;
        ActualizeFields();
    }//GEN-LAST:event_lblMsecondsMouseWheelMoved

    private void edtDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDurationActionPerformed
        try {
            m_lPauseMillis = Integer.parseInt( edtDuration.getText());
            ActualizeFields();
        }
        catch( NumberFormatException ex) {
            logger.warn( "NumberFormatException caught!", ex);
            edtDuration.setText( "" + m_lPauseMillis);
        }
    }//GEN-LAST:event_edtDurationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField edtDuration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblHours;
    private javax.swing.JLabel lblMinutes;
    private javax.swing.JLabel lblMseconds;
    private javax.swing.JLabel lblSeconds;
    // End of variables declaration//GEN-END:variables
}
