/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_constructor.newService;

import hvv_constructor.HVV_Constructor;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author yaroslav
 */
public class PnlServSound extends javax.swing.JPanel {

    private final HVV_Constructor theApp;
    
    /**
     * Creates new form pnlServeSound
     */
    public PnlServSound( HVV_Constructor app) {
        theApp = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWavFile = new javax.swing.JLabel();
        edtWavFile = new javax.swing.JTextField();
        btnBrowseWavFile = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setPreferredSize(new java.awt.Dimension(900, 400));
        setLayout(null);

        lblWavFile.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblWavFile.setText("<html><u>Проигрываемый wav-файл:</u><html>");
        add(lblWavFile);
        lblWavFile.setBounds(30, 30, 300, 30);

        edtWavFile.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        edtWavFile.setToolTipText("");
        edtWavFile.setEnabled(false);
        add(edtWavFile);
        edtWavFile.setBounds(30, 70, 850, 40);

        btnBrowseWavFile.setText("Обзор");
        btnBrowseWavFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseWavFileActionPerformed(evt);
            }
        });
        add(btnBrowseWavFile);
        btnBrowseWavFile.setBounds(340, 20, 130, 40);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Inner class for FileOpen dialog filter
     */
    class MyWavFilter extends FileFilter {

        @Override
        public boolean accept( File f) {
            if (f.isDirectory()) {
                return true;
            }
            
            String extension = Utils.getExtension( f);
            if( extension != null) {
                if( extension.equals( Utils.wav))
                    return true;
                else
                    return false;
            }

            return false;
        }

        @Override
        public String getDescription() {
            return "WAV files";
        }
        
    }
    
    private void btnBrowseWavFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseWavFileActionPerformed
        //Create a file chooser
        final JFileChooser fc = new JFileChooser();
        
        fc.setCurrentDirectory( new File( theApp.GetAMSRoot() + "/res/sound"));
        
        fc.setFileFilter( new MyWavFilter());
        
        int returnVal = fc.showOpenDialog( this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            /*
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            log.append("Opening: " + file.getName() + "." + newline);
            */
            File file = fc.getSelectedFile();
            edtWavFile.setText( file.getAbsolutePath());
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_btnBrowseWavFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseWavFile;
    public javax.swing.JTextField edtWavFile;
    private javax.swing.JLabel lblWavFile;
    // End of variables declaration//GEN-END:variables
}
