/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_constructor.newVacuum;

import hvv_constructor.HVV_Constructor;
import hvv_devices.HVV_VacuumDevices;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author yaroslav
 */
public class PnlVacSet extends javax.swing.JPanel {

    private HVV_Constructor theApp;
    private DefaultComboBoxModel cmbObjectModel;
    
    /**
     * Creates new form PnlVacSet
     */
    public PnlVacSet( HVV_Constructor app) {
        initComponents();
        
        theApp = app;
        cmbObjectModel = new DefaultComboBoxModel();
        HVV_VacuumDevices.getInstance().fillComboSet( cmbObjectModel);
        cmbObject.setModel( cmbObjectModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbObject = new javax.swing.JComboBox();
        edtSetValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setLayout(null);

        jLabel1.setText("Уставка:");
        add(jLabel1);
        jLabel1.setBounds(30, 130, 410, 30);

        cmbObject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "16A. Регулятор расхода газа MKS 1179 (O2)", "16B. Регулятор расхода газа MKS 1179 (Ne20)", "16C. Регулятор расхода газа MKS 1179 (He4)", "17A. Регулятор расхода газа MKS M330B (Ne20+22)", "17B. Регулятор расхода газа MKS M330B (He3)", "018. Регулятор расхода газа MKS 1480A (N2)" }));
        add(cmbObject);
        cmbObject.setBounds(30, 70, 820, 40);
        add(edtSetValue);
        edtSetValue.setBounds(30, 170, 150, 40);

        jLabel2.setText("Задать уставку для:");
        add(jLabel2);
        jLabel2.setBounds(30, 30, 410, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cmbObject;
    public javax.swing.JTextField edtSetValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
