/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_constructor.newVacuum;

import hvv_constructor.HVV_Constructor;
import javax.swing.DefaultComboBoxModel;
import hvv_devices.*;

/**
 *
 * @author yaroslav
 */
public class PnlVacTurnOn extends javax.swing.JPanel {

    HVV_Constructor theApp;
    private DefaultComboBoxModel cmbObjectModel;
    /**
     * Creates new form PnlVacTurnOn
     */
    public PnlVacTurnOn( HVV_Constructor app) {
        initComponents();
        
        theApp = app;
        cmbObjectModel = new DefaultComboBoxModel();
        HVV_VacuumDevices.getInstance().fillComboTurnOnOff( cmbObjectModel);
        cmbObject.setModel( cmbObjectModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbObject = new javax.swing.JComboBox();

        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setLayout(null);

        jLabel1.setText("Включаемый объект:");
        add(jLabel1);
        jLabel1.setBounds(30, 30, 410, 30);

        cmbObject.setMaximumRowCount(12);
        cmbObject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00А. Контур контроля вакуума", "001. Насос форвакуумный", "002. Насос турбомолекулярный", "003. Откачная станция" }));
        add(cmbObject);
        cmbObject.setBounds(30, 70, 410, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cmbObject;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
