/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_constructor.newHv;

/**
 *
 * @author yaroslav
 */
public class PnlHVFan extends javax.swing.JPanel {

    /**
     * Creates new form PnlHVVibration
     */
    public PnlHVFan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGVibration = new javax.swing.ButtonGroup();
        radFanOn = new javax.swing.JRadioButton();
        radFanOff = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setLayout(null);

        btnGVibration.add(radFanOn);
        radFanOn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        radFanOn.setSelected(true);
        radFanOn.setText("Включить");
        add(radFanOn);
        radFanOn.setBounds(30, 30, 160, 26);

        btnGVibration.add(radFanOff);
        radFanOff.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        radFanOff.setText("Выключить");
        add(radFanOff);
        radFanOff.setBounds(30, 80, 160, 26);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGVibration;
    public javax.swing.JRadioButton radFanOff;
    public javax.swing.JRadioButton radFanOn;
    // End of variables declaration//GEN-END:variables
}
