/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_constructor.newHv;

/**
 *
 * @author yaroslav
 */
public class PnlHVMainSwitcher extends javax.swing.JPanel {

    /**
     * Creates new form PnlHVMainSwicther
     */
    public PnlHVMainSwitcher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radGMainSwitcher = new javax.swing.ButtonGroup();
        radMainSwitcherOn = new javax.swing.JRadioButton();
        radMainSwitcherOff = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setLayout(null);

        radGMainSwitcher.add(radMainSwitcherOn);
        radMainSwitcherOn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        radMainSwitcherOn.setForeground(new java.awt.Color(200, 0, 0));
        radMainSwitcherOn.setText("Подать");
        add(radMainSwitcherOn);
        radMainSwitcherOn.setBounds(30, 30, 95, 26);

        radGMainSwitcher.add(radMainSwitcherOff);
        radMainSwitcherOff.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        radMainSwitcherOff.setForeground(new java.awt.Color(0, 200, 0));
        radMainSwitcherOff.setSelected(true);
        radMainSwitcherOff.setText("Снять");
        add(radMainSwitcherOff);
        radMainSwitcherOff.setBounds(30, 80, 84, 26);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup radGMainSwitcher;
    public javax.swing.JRadioButton radMainSwitcherOff;
    public javax.swing.JRadioButton radMainSwitcherOn;
    // End of variables declaration//GEN-END:variables
}
