/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_constructor.newHv;

/**
 *
 * @author yaroslav
 */
public class PnlHVRegime extends javax.swing.JPanel {

    /**
     * Creates new form PnlHVRegime
     */
    public PnlHVRegime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radGRegime = new javax.swing.ButtonGroup();
        radRegimeManual = new javax.swing.JRadioButton();
        radRegimeUAC = new javax.swing.JRadioButton();
        radRegimeProcessing = new javax.swing.JRadioButton();
        radRegimeEdge = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setLayout(null);

        radGRegime.add(radRegimeManual);
        radRegimeManual.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        radRegimeManual.setSelected(true);
        radRegimeManual.setText("Ручной режим");
        add(radRegimeManual);
        radRegimeManual.setBounds(30, 30, 245, 23);

        radGRegime.add(radRegimeUAC);
        radRegimeUAC.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        radRegimeUAC.setText("Измерение ВАХ");
        add(radRegimeUAC);
        radRegimeUAC.setBounds(30, 59, 245, 23);

        radGRegime.add(radRegimeProcessing);
        radRegimeProcessing.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        radRegimeProcessing.setText("Обработка");
        add(radRegimeProcessing);
        radRegimeProcessing.setBounds(30, 88, 245, 23);

        radGRegime.add(radRegimeEdge);
        radRegimeEdge.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        radRegimeEdge.setText("Измерение порогового тока");
        add(radRegimeEdge);
        radRegimeEdge.setBounds(30, 117, 245, 23);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup radGRegime;
    private javax.swing.JRadioButton radRegimeEdge;
    private javax.swing.JRadioButton radRegimeManual;
    private javax.swing.JRadioButton radRegimeProcessing;
    private javax.swing.JRadioButton radRegimeUAC;
    // End of variables declaration//GEN-END:variables
}
