/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_constructor.newHv;

/**
 *
 * @author yaroslav
 */
public class PnlHVPreset extends javax.swing.JPanel {

    /**
     * Creates new form pnlServPause
     */
    public PnlHVPreset() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edtPreset = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("<html><u>Уставка тока, мкА</u><html>");
        add(jLabel1);
        jLabel1.setBounds(30, 30, 830, 30);

        edtPreset.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edtPreset.setText("1000");
        edtPreset.setToolTipText("");
        add(edtPreset);
        edtPreset.setBounds(30, 70, 210, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField edtPreset;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
