/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_constructor.newHv;

import javax.swing.ButtonGroup;

/**
 *
 * @author yaroslav
 */
public class PnlHVChannels extends javax.swing.JPanel {

    /**
     * Creates new form PnlHVChannels
     */
    public PnlHVChannels() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGTDev1a = new javax.swing.ButtonGroup();
        btnGTDev2a = new javax.swing.ButtonGroup();
        btnGTDev3a = new javax.swing.ButtonGroup();
        btnGTDev4a = new javax.swing.ButtonGroup();
        btnGTDev5a = new javax.swing.ButtonGroup();
        btnGTDev6a = new javax.swing.ButtonGroup();
        btnGTDev7a = new javax.swing.ButtonGroup();
        btnGTDev8a = new javax.swing.ButtonGroup();
        btnGTDev1t = new javax.swing.ButtonGroup();
        btnGTDev2t = new javax.swing.ButtonGroup();
        btnGTDev3t = new javax.swing.ButtonGroup();
        btnGTDev4t = new javax.swing.ButtonGroup();
        btnGTDev5t = new javax.swing.ButtonGroup();
        btnGTDev6t = new javax.swing.ButtonGroup();
        btnGTDev7t = new javax.swing.ButtonGroup();
        btnGTDev8t = new javax.swing.ButtonGroup();
        radTDev1aNoChange = new javax.swing.JRadioButton();
        radTDev1aOn = new javax.swing.JRadioButton();
        radTDev1aOff = new javax.swing.JRadioButton();
        radTDev2aNoChange = new javax.swing.JRadioButton();
        radTDev2aOn = new javax.swing.JRadioButton();
        radTDev2aOff = new javax.swing.JRadioButton();
        radTDev3aNoChange = new javax.swing.JRadioButton();
        radTDev3aOn = new javax.swing.JRadioButton();
        radTDev3aOff = new javax.swing.JRadioButton();
        radTDev4aNoChange = new javax.swing.JRadioButton();
        radTDev4aOn = new javax.swing.JRadioButton();
        radTDev4aOff = new javax.swing.JRadioButton();
        radTDev5aNoChange = new javax.swing.JRadioButton();
        radTDev5aOn = new javax.swing.JRadioButton();
        radTDev5aOff = new javax.swing.JRadioButton();
        radTDev6aNoChange = new javax.swing.JRadioButton();
        radTDev6aOn = new javax.swing.JRadioButton();
        radTDev6aOff = new javax.swing.JRadioButton();
        radTDev7aNoChange = new javax.swing.JRadioButton();
        radTDev7aOn = new javax.swing.JRadioButton();
        radTDev7aOff = new javax.swing.JRadioButton();
        radTDev8aNoChange = new javax.swing.JRadioButton();
        radTDev8aOn = new javax.swing.JRadioButton();
        radTDev8aOff = new javax.swing.JRadioButton();
        radTDev1tNoChange = new javax.swing.JRadioButton();
        radTDev1tOn = new javax.swing.JRadioButton();
        radTDev1tOff = new javax.swing.JRadioButton();
        radTDev2tNoChange = new javax.swing.JRadioButton();
        radTDev2tOn = new javax.swing.JRadioButton();
        radTDev2tOff = new javax.swing.JRadioButton();
        radTDev3tNoChange = new javax.swing.JRadioButton();
        radTDev3tOn = new javax.swing.JRadioButton();
        radTDev3tOff = new javax.swing.JRadioButton();
        radTDev4tNoChange = new javax.swing.JRadioButton();
        radTDev4tOn = new javax.swing.JRadioButton();
        radTDev4tOff = new javax.swing.JRadioButton();
        radTDev5tNoChange = new javax.swing.JRadioButton();
        radTDev5tOn = new javax.swing.JRadioButton();
        radTDev5tOff = new javax.swing.JRadioButton();
        radTDev6tNoChange = new javax.swing.JRadioButton();
        radTDev6tOn = new javax.swing.JRadioButton();
        radTDev6tOff = new javax.swing.JRadioButton();
        radTDev7tNoChange = new javax.swing.JRadioButton();
        radTDev7tOn = new javax.swing.JRadioButton();
        radTDev7tOff = new javax.swing.JRadioButton();
        radTDev8tNoChange = new javax.swing.JRadioButton();
        radTDev8tOn = new javax.swing.JRadioButton();
        radTDev8tOff = new javax.swing.JRadioButton();
        btnAnodesOff = new javax.swing.JButton();
        btnAnodesOn = new javax.swing.JButton();
        btnTubusOn = new javax.swing.JButton();
        btnTubusOff = new javax.swing.JButton();
        btnTDev1On = new javax.swing.JButton();
        btnTDev2On = new javax.swing.JButton();
        btnTDev3On = new javax.swing.JButton();
        btnTDev4On = new javax.swing.JButton();
        btnTDev5On = new javax.swing.JButton();
        btnTDev6On = new javax.swing.JButton();
        btnTDev7On = new javax.swing.JButton();
        btnTDev8On = new javax.swing.JButton();
        btnTDev1Off = new javax.swing.JButton();
        btnTDev2Off = new javax.swing.JButton();
        btnTDev3Off = new javax.swing.JButton();
        btnTDev4Off = new javax.swing.JButton();
        btnTDev5Off = new javax.swing.JButton();
        btnTDev6Off = new javax.swing.JButton();
        btnTDev7Off = new javax.swing.JButton();
        btnTDev8Off = new javax.swing.JButton();
        chkCheckAdmin = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setPreferredSize(new java.awt.Dimension(900, 400));
        setLayout(null);

        btnGTDev1a.add(radTDev1aNoChange);
        radTDev1aNoChange.setSelected(true);
        radTDev1aNoChange.setText("без изм.");
        radTDev1aNoChange.setToolTipText("");
        radTDev1aNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev1aNoChange);
        radTDev1aNoChange.setBounds(110, 90, 90, 20);

        btnGTDev1a.add(radTDev1aOn);
        radTDev1aOn.setText("вкл");
        radTDev1aOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev1aOn);
        radTDev1aOn.setBounds(110, 110, 90, 20);

        btnGTDev1a.add(radTDev1aOff);
        radTDev1aOff.setText("выкл");
        radTDev1aOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev1aOff);
        radTDev1aOff.setBounds(110, 130, 90, 20);

        btnGTDev2a.add(radTDev2aNoChange);
        radTDev2aNoChange.setSelected(true);
        radTDev2aNoChange.setText("без изм.");
        radTDev2aNoChange.setToolTipText("");
        radTDev2aNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev2aNoChange);
        radTDev2aNoChange.setBounds(200, 90, 90, 20);

        btnGTDev2a.add(radTDev2aOn);
        radTDev2aOn.setText("вкл");
        radTDev2aOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev2aOn);
        radTDev2aOn.setBounds(200, 110, 90, 20);

        btnGTDev2a.add(radTDev2aOff);
        radTDev2aOff.setText("выкл");
        radTDev2aOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev2aOff);
        radTDev2aOff.setBounds(200, 130, 90, 20);

        btnGTDev3a.add(radTDev3aNoChange);
        radTDev3aNoChange.setSelected(true);
        radTDev3aNoChange.setText("без изм.");
        radTDev3aNoChange.setToolTipText("");
        radTDev3aNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev3aNoChange);
        radTDev3aNoChange.setBounds(290, 90, 90, 20);

        btnGTDev3a.add(radTDev3aOn);
        radTDev3aOn.setText("вкл");
        radTDev3aOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev3aOn);
        radTDev3aOn.setBounds(290, 110, 90, 20);

        btnGTDev3a.add(radTDev3aOff);
        radTDev3aOff.setText("выкл");
        radTDev3aOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev3aOff);
        radTDev3aOff.setBounds(290, 130, 90, 20);

        btnGTDev4a.add(radTDev4aNoChange);
        radTDev4aNoChange.setSelected(true);
        radTDev4aNoChange.setText("без изм.");
        radTDev4aNoChange.setToolTipText("");
        radTDev4aNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev4aNoChange);
        radTDev4aNoChange.setBounds(380, 90, 90, 20);

        btnGTDev4a.add(radTDev4aOn);
        radTDev4aOn.setText("вкл");
        radTDev4aOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev4aOn);
        radTDev4aOn.setBounds(380, 110, 90, 20);

        btnGTDev4a.add(radTDev4aOff);
        radTDev4aOff.setText("выкл");
        radTDev4aOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev4aOff);
        radTDev4aOff.setBounds(380, 130, 90, 20);

        btnGTDev5a.add(radTDev5aNoChange);
        radTDev5aNoChange.setSelected(true);
        radTDev5aNoChange.setText("без изм.");
        radTDev5aNoChange.setToolTipText("");
        radTDev5aNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev5aNoChange);
        radTDev5aNoChange.setBounds(470, 90, 90, 20);

        btnGTDev5a.add(radTDev5aOn);
        radTDev5aOn.setText("вкл");
        radTDev5aOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev5aOn);
        radTDev5aOn.setBounds(470, 110, 90, 20);

        btnGTDev5a.add(radTDev5aOff);
        radTDev5aOff.setText("выкл");
        radTDev5aOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev5aOff);
        radTDev5aOff.setBounds(470, 130, 90, 20);

        btnGTDev6a.add(radTDev6aNoChange);
        radTDev6aNoChange.setSelected(true);
        radTDev6aNoChange.setText("без изм.");
        radTDev6aNoChange.setToolTipText("");
        radTDev6aNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev6aNoChange);
        radTDev6aNoChange.setBounds(560, 90, 90, 20);

        btnGTDev6a.add(radTDev6aOn);
        radTDev6aOn.setText("вкл");
        radTDev6aOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev6aOn);
        radTDev6aOn.setBounds(560, 110, 90, 20);

        btnGTDev6a.add(radTDev6aOff);
        radTDev6aOff.setText("выкл");
        radTDev6aOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev6aOff);
        radTDev6aOff.setBounds(560, 130, 90, 20);

        btnGTDev7a.add(radTDev7aNoChange);
        radTDev7aNoChange.setSelected(true);
        radTDev7aNoChange.setText("без изм.");
        radTDev7aNoChange.setToolTipText("");
        radTDev7aNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev7aNoChange);
        radTDev7aNoChange.setBounds(650, 90, 90, 20);

        btnGTDev7a.add(radTDev7aOn);
        radTDev7aOn.setText("вкл");
        radTDev7aOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev7aOn);
        radTDev7aOn.setBounds(650, 110, 90, 20);

        btnGTDev7a.add(radTDev7aOff);
        radTDev7aOff.setText("выкл");
        radTDev7aOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev7aOff);
        radTDev7aOff.setBounds(650, 130, 90, 20);

        btnGTDev8a.add(radTDev8aNoChange);
        radTDev8aNoChange.setSelected(true);
        radTDev8aNoChange.setText("без изм.");
        radTDev8aNoChange.setToolTipText("");
        radTDev8aNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev8aNoChange);
        radTDev8aNoChange.setBounds(740, 90, 90, 20);

        btnGTDev8a.add(radTDev8aOn);
        radTDev8aOn.setText("вкл");
        radTDev8aOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev8aOn);
        radTDev8aOn.setBounds(740, 110, 90, 20);

        btnGTDev8a.add(radTDev8aOff);
        radTDev8aOff.setText("выкл");
        radTDev8aOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev8aOff);
        radTDev8aOff.setBounds(740, 130, 90, 20);

        btnGTDev1t.add(radTDev1tNoChange);
        radTDev1tNoChange.setSelected(true);
        radTDev1tNoChange.setText("без изм.");
        radTDev1tNoChange.setToolTipText("");
        radTDev1tNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev1tNoChange);
        radTDev1tNoChange.setBounds(110, 170, 90, 20);

        btnGTDev1t.add(radTDev1tOn);
        radTDev1tOn.setText("вкл");
        radTDev1tOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev1tOn);
        radTDev1tOn.setBounds(110, 190, 90, 20);

        btnGTDev1t.add(radTDev1tOff);
        radTDev1tOff.setText("выкл");
        radTDev1tOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev1tOff);
        radTDev1tOff.setBounds(110, 210, 90, 20);

        btnGTDev2t.add(radTDev2tNoChange);
        radTDev2tNoChange.setSelected(true);
        radTDev2tNoChange.setText("без изм.");
        radTDev2tNoChange.setToolTipText("");
        radTDev2tNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev2tNoChange);
        radTDev2tNoChange.setBounds(200, 170, 90, 20);

        btnGTDev2t.add(radTDev2tOn);
        radTDev2tOn.setText("вкл");
        radTDev2tOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev2tOn);
        radTDev2tOn.setBounds(200, 190, 90, 20);

        btnGTDev2t.add(radTDev2tOff);
        radTDev2tOff.setText("выкл");
        radTDev2tOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev2tOff);
        radTDev2tOff.setBounds(200, 210, 90, 20);

        btnGTDev3t.add(radTDev3tNoChange);
        radTDev3tNoChange.setSelected(true);
        radTDev3tNoChange.setText("без изм.");
        radTDev3tNoChange.setToolTipText("");
        radTDev3tNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev3tNoChange);
        radTDev3tNoChange.setBounds(290, 170, 90, 20);

        btnGTDev3t.add(radTDev3tOn);
        radTDev3tOn.setText("вкл");
        radTDev3tOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev3tOn);
        radTDev3tOn.setBounds(290, 190, 90, 20);

        btnGTDev3t.add(radTDev3tOff);
        radTDev3tOff.setText("выкл");
        radTDev3tOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev3tOff);
        radTDev3tOff.setBounds(290, 210, 90, 20);

        btnGTDev4t.add(radTDev4tNoChange);
        radTDev4tNoChange.setSelected(true);
        radTDev4tNoChange.setText("без изм.");
        radTDev4tNoChange.setToolTipText("");
        radTDev4tNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev4tNoChange);
        radTDev4tNoChange.setBounds(380, 170, 90, 20);

        btnGTDev4t.add(radTDev4tOn);
        radTDev4tOn.setText("вкл");
        radTDev4tOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev4tOn);
        radTDev4tOn.setBounds(380, 190, 90, 20);

        btnGTDev4t.add(radTDev4tOff);
        radTDev4tOff.setText("выкл");
        radTDev4tOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev4tOff);
        radTDev4tOff.setBounds(380, 210, 90, 20);

        btnGTDev5t.add(radTDev5tNoChange);
        radTDev5tNoChange.setSelected(true);
        radTDev5tNoChange.setText("без изм.");
        radTDev5tNoChange.setToolTipText("");
        radTDev5tNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev5tNoChange);
        radTDev5tNoChange.setBounds(470, 170, 90, 20);

        btnGTDev5t.add(radTDev5tOn);
        radTDev5tOn.setText("вкл");
        radTDev5tOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev5tOn);
        radTDev5tOn.setBounds(470, 190, 90, 20);

        btnGTDev5t.add(radTDev5tOff);
        radTDev5tOff.setText("выкл");
        radTDev5tOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev5tOff);
        radTDev5tOff.setBounds(470, 210, 90, 20);

        btnGTDev6t.add(radTDev6tNoChange);
        radTDev6tNoChange.setSelected(true);
        radTDev6tNoChange.setText("без изм.");
        radTDev6tNoChange.setToolTipText("");
        radTDev6tNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev6tNoChange);
        radTDev6tNoChange.setBounds(560, 170, 90, 20);

        btnGTDev6t.add(radTDev6tOn);
        radTDev6tOn.setText("вкл");
        radTDev6tOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev6tOn);
        radTDev6tOn.setBounds(560, 190, 90, 20);

        btnGTDev6t.add(radTDev6tOff);
        radTDev6tOff.setText("выкл");
        radTDev6tOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev6tOff);
        radTDev6tOff.setBounds(560, 210, 90, 20);

        btnGTDev7t.add(radTDev7tNoChange);
        radTDev7tNoChange.setSelected(true);
        radTDev7tNoChange.setText("без изм.");
        radTDev7tNoChange.setToolTipText("");
        radTDev7tNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev7tNoChange);
        radTDev7tNoChange.setBounds(650, 170, 90, 20);

        btnGTDev7t.add(radTDev7tOn);
        radTDev7tOn.setText("вкл");
        radTDev7tOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev7tOn);
        radTDev7tOn.setBounds(650, 190, 90, 20);

        btnGTDev7t.add(radTDev7tOff);
        radTDev7tOff.setText("выкл");
        radTDev7tOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev7tOff);
        radTDev7tOff.setBounds(650, 210, 90, 20);

        btnGTDev8t.add(radTDev8tNoChange);
        radTDev8tNoChange.setSelected(true);
        radTDev8tNoChange.setText("без изм.");
        radTDev8tNoChange.setToolTipText("");
        radTDev8tNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev8tNoChange);
        radTDev8tNoChange.setBounds(740, 170, 90, 20);

        btnGTDev8t.add(radTDev8tOn);
        radTDev8tOn.setText("вкл");
        radTDev8tOn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev8tOn);
        radTDev8tOn.setBounds(740, 190, 90, 20);

        btnGTDev8t.add(radTDev8tOff);
        radTDev8tOff.setText("выкл");
        radTDev8tOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(radTDev8tOff);
        radTDev8tOff.setBounds(740, 210, 90, 20);

        btnAnodesOff.setBackground(java.awt.Color.green);
        btnAnodesOff.setText("Аноды");
        btnAnodesOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnodesOffActionPerformed(evt);
            }
        });
        add(btnAnodesOff);
        btnAnodesOff.setBounds(840, 90, 110, 60);

        btnAnodesOn.setBackground(java.awt.Color.pink);
        btnAnodesOn.setText("Аноды");
        btnAnodesOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnodesOnActionPerformed(evt);
            }
        });
        add(btnAnodesOn);
        btnAnodesOn.setBounds(2, 90, 100, 60);

        btnTubusOn.setBackground(java.awt.Color.pink);
        btnTubusOn.setText("Штенгели");
        btnTubusOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTubusOnActionPerformed(evt);
            }
        });
        add(btnTubusOn);
        btnTubusOn.setBounds(0, 170, 100, 60);

        btnTubusOff.setBackground(java.awt.Color.green);
        btnTubusOff.setText("Штенгели");
        btnTubusOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTubusOffActionPerformed(evt);
            }
        });
        add(btnTubusOff);
        btnTubusOff.setBounds(840, 170, 110, 60);

        btnTDev1On.setBackground(java.awt.Color.pink);
        btnTDev1On.setText("ЛГ 1");
        btnTDev1On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev1OnActionPerformed(evt);
            }
        });
        add(btnTDev1On);
        btnTDev1On.setBounds(110, 40, 90, 40);

        btnTDev2On.setBackground(java.awt.Color.pink);
        btnTDev2On.setText("ЛГ 2");
        btnTDev2On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev2OnActionPerformed(evt);
            }
        });
        add(btnTDev2On);
        btnTDev2On.setBounds(200, 40, 90, 40);

        btnTDev3On.setBackground(java.awt.Color.pink);
        btnTDev3On.setText("ЛГ 3");
        btnTDev3On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev3OnActionPerformed(evt);
            }
        });
        add(btnTDev3On);
        btnTDev3On.setBounds(290, 40, 90, 40);

        btnTDev4On.setBackground(java.awt.Color.pink);
        btnTDev4On.setText("ЛГ 4");
        btnTDev4On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev4OnActionPerformed(evt);
            }
        });
        add(btnTDev4On);
        btnTDev4On.setBounds(380, 40, 90, 40);

        btnTDev5On.setBackground(java.awt.Color.pink);
        btnTDev5On.setText("ЛГ 5");
        btnTDev5On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev5OnActionPerformed(evt);
            }
        });
        add(btnTDev5On);
        btnTDev5On.setBounds(470, 40, 90, 40);

        btnTDev6On.setBackground(java.awt.Color.pink);
        btnTDev6On.setText("ЛГ 6");
        btnTDev6On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev6OnActionPerformed(evt);
            }
        });
        add(btnTDev6On);
        btnTDev6On.setBounds(560, 40, 90, 40);

        btnTDev7On.setBackground(java.awt.Color.pink);
        btnTDev7On.setText("ЛГ 7");
        btnTDev7On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev7OnActionPerformed(evt);
            }
        });
        add(btnTDev7On);
        btnTDev7On.setBounds(650, 40, 90, 40);

        btnTDev8On.setBackground(java.awt.Color.pink);
        btnTDev8On.setText("ЛГ 8");
        btnTDev8On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev8OnActionPerformed(evt);
            }
        });
        add(btnTDev8On);
        btnTDev8On.setBounds(740, 40, 90, 40);

        btnTDev1Off.setBackground(java.awt.Color.green);
        btnTDev1Off.setText("ЛГ 1");
        btnTDev1Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev1OffActionPerformed(evt);
            }
        });
        add(btnTDev1Off);
        btnTDev1Off.setBounds(110, 240, 90, 40);

        btnTDev2Off.setBackground(java.awt.Color.green);
        btnTDev2Off.setText("ЛГ 2");
        btnTDev2Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev2OffActionPerformed(evt);
            }
        });
        add(btnTDev2Off);
        btnTDev2Off.setBounds(200, 240, 90, 40);

        btnTDev3Off.setBackground(java.awt.Color.green);
        btnTDev3Off.setText("ЛГ 3");
        btnTDev3Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev3OffActionPerformed(evt);
            }
        });
        add(btnTDev3Off);
        btnTDev3Off.setBounds(290, 240, 90, 40);

        btnTDev4Off.setBackground(java.awt.Color.green);
        btnTDev4Off.setText("ЛГ 4");
        btnTDev4Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev4OffActionPerformed(evt);
            }
        });
        add(btnTDev4Off);
        btnTDev4Off.setBounds(380, 240, 90, 40);

        btnTDev5Off.setBackground(java.awt.Color.green);
        btnTDev5Off.setText("ЛГ 5");
        btnTDev5Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev5OffActionPerformed(evt);
            }
        });
        add(btnTDev5Off);
        btnTDev5Off.setBounds(470, 240, 90, 40);

        btnTDev6Off.setBackground(java.awt.Color.green);
        btnTDev6Off.setText("ЛГ 6");
        btnTDev6Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev6OffActionPerformed(evt);
            }
        });
        add(btnTDev6Off);
        btnTDev6Off.setBounds(560, 240, 90, 40);

        btnTDev7Off.setBackground(java.awt.Color.green);
        btnTDev7Off.setText("ЛГ 7");
        btnTDev7Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev7OffActionPerformed(evt);
            }
        });
        add(btnTDev7Off);
        btnTDev7Off.setBounds(650, 240, 90, 40);

        btnTDev8Off.setBackground(java.awt.Color.green);
        btnTDev8Off.setText("ЛГ 8");
        btnTDev8Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDev8OffActionPerformed(evt);
            }
        });
        add(btnTDev8Off);
        btnTDev8Off.setBounds(740, 240, 90, 40);

        chkCheckAdmin.setText("перед включением соотнести с информацией от административного модуля");
        add(chkCheckAdmin);
        chkCheckAdmin.setBounds(110, 10, 720, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTDev8OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev8OnActionPerformed
        radTDev8aOn.setSelected( true);  radTDev8tOn.setSelected( true);
    }//GEN-LAST:event_btnTDev8OnActionPerformed

    private void btnAnodesOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnodesOnActionPerformed
        radTDev1aOn.setSelected( true);
        radTDev2aOn.setSelected( true);
        radTDev3aOn.setSelected( true);
        radTDev4aOn.setSelected( true);
        radTDev5aOn.setSelected( true);
        radTDev6aOn.setSelected( true);
        radTDev7aOn.setSelected( true);
        radTDev8aOn.setSelected( true);
    }//GEN-LAST:event_btnAnodesOnActionPerformed

    private void btnAnodesOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnodesOffActionPerformed
        radTDev1aOff.setSelected( true);
        radTDev2aOff.setSelected( true);
        radTDev3aOff.setSelected( true);
        radTDev4aOff.setSelected( true);
        radTDev5aOff.setSelected( true);
        radTDev6aOff.setSelected( true);
        radTDev7aOff.setSelected( true);
        radTDev8aOff.setSelected( true);
    }//GEN-LAST:event_btnAnodesOffActionPerformed

    private void btnTubusOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTubusOnActionPerformed
        radTDev1tOn.setSelected( true);
        radTDev2tOn.setSelected( true);
        radTDev3tOn.setSelected( true);
        radTDev4tOn.setSelected( true);
        radTDev5tOn.setSelected( true);
        radTDev6tOn.setSelected( true);
        radTDev7tOn.setSelected( true);
        radTDev8tOn.setSelected( true);
    }//GEN-LAST:event_btnTubusOnActionPerformed

    private void btnTubusOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTubusOffActionPerformed
        radTDev1tOff.setSelected( true);
        radTDev2tOff.setSelected( true);
        radTDev3tOff.setSelected( true);
        radTDev4tOff.setSelected( true);
        radTDev5tOff.setSelected( true);
        radTDev6tOff.setSelected( true);
        radTDev7tOff.setSelected( true);
        radTDev8tOff.setSelected( true);
    }//GEN-LAST:event_btnTubusOffActionPerformed

    private void btnTDev1OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev1OnActionPerformed
        radTDev1aOn.setSelected( true);  radTDev1tOn.setSelected( true);
    }//GEN-LAST:event_btnTDev1OnActionPerformed

    private void btnTDev2OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev2OnActionPerformed
        radTDev2aOn.setSelected( true);  radTDev2tOn.setSelected( true);
    }//GEN-LAST:event_btnTDev2OnActionPerformed

    private void btnTDev3OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev3OnActionPerformed
        radTDev3aOn.setSelected( true);  radTDev3tOn.setSelected( true);
    }//GEN-LAST:event_btnTDev3OnActionPerformed

    private void btnTDev4OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev4OnActionPerformed
        radTDev4aOn.setSelected( true);  radTDev4tOn.setSelected( true);
    }//GEN-LAST:event_btnTDev4OnActionPerformed

    private void btnTDev5OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev5OnActionPerformed
        radTDev5aOn.setSelected( true);  radTDev5tOn.setSelected( true);
    }//GEN-LAST:event_btnTDev5OnActionPerformed

    private void btnTDev6OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev6OnActionPerformed
        radTDev6aOn.setSelected( true);  radTDev6tOn.setSelected( true);
    }//GEN-LAST:event_btnTDev6OnActionPerformed

    private void btnTDev7OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev7OnActionPerformed
        radTDev7aOn.setSelected( true);  radTDev7tOn.setSelected( true);
    }//GEN-LAST:event_btnTDev7OnActionPerformed

    private void btnTDev1OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev1OffActionPerformed
        radTDev1aOff.setSelected( true);  radTDev1tOff.setSelected( true);
    }//GEN-LAST:event_btnTDev1OffActionPerformed

    private void btnTDev2OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev2OffActionPerformed
        radTDev2aOff.setSelected( true);  radTDev2tOff.setSelected( true);
    }//GEN-LAST:event_btnTDev2OffActionPerformed

    private void btnTDev3OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev3OffActionPerformed
        radTDev3aOff.setSelected( true);  radTDev3tOff.setSelected( true);
    }//GEN-LAST:event_btnTDev3OffActionPerformed

    private void btnTDev4OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev4OffActionPerformed
        radTDev4aOff.setSelected( true);  radTDev4tOff.setSelected( true);
    }//GEN-LAST:event_btnTDev4OffActionPerformed

    private void btnTDev5OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev5OffActionPerformed
        radTDev5aOff.setSelected( true);  radTDev5tOff.setSelected( true);
    }//GEN-LAST:event_btnTDev5OffActionPerformed

    private void btnTDev6OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev6OffActionPerformed
        radTDev6aOff.setSelected( true);  radTDev6tOff.setSelected( true);
    }//GEN-LAST:event_btnTDev6OffActionPerformed

    private void btnTDev7OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev7OffActionPerformed
        radTDev7aOff.setSelected( true);  radTDev7tOff.setSelected( true);
    }//GEN-LAST:event_btnTDev7OffActionPerformed

    private void btnTDev8OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDev8OffActionPerformed
        radTDev8aOff.setSelected( true);  radTDev8tOff.setSelected( true);
    }//GEN-LAST:event_btnTDev8OffActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnodesOff;
    private javax.swing.JButton btnAnodesOn;
    private javax.swing.ButtonGroup btnGTDev1a;
    private javax.swing.ButtonGroup btnGTDev1t;
    private javax.swing.ButtonGroup btnGTDev2a;
    private javax.swing.ButtonGroup btnGTDev2t;
    private javax.swing.ButtonGroup btnGTDev3a;
    private javax.swing.ButtonGroup btnGTDev3t;
    private javax.swing.ButtonGroup btnGTDev4a;
    private javax.swing.ButtonGroup btnGTDev4t;
    private javax.swing.ButtonGroup btnGTDev5a;
    private javax.swing.ButtonGroup btnGTDev5t;
    private javax.swing.ButtonGroup btnGTDev6a;
    private javax.swing.ButtonGroup btnGTDev6t;
    private javax.swing.ButtonGroup btnGTDev7a;
    private javax.swing.ButtonGroup btnGTDev7t;
    private javax.swing.ButtonGroup btnGTDev8a;
    private javax.swing.ButtonGroup btnGTDev8t;
    private javax.swing.JButton btnTDev1Off;
    private javax.swing.JButton btnTDev1On;
    private javax.swing.JButton btnTDev2Off;
    private javax.swing.JButton btnTDev2On;
    private javax.swing.JButton btnTDev3Off;
    private javax.swing.JButton btnTDev3On;
    private javax.swing.JButton btnTDev4Off;
    private javax.swing.JButton btnTDev4On;
    private javax.swing.JButton btnTDev5Off;
    private javax.swing.JButton btnTDev5On;
    private javax.swing.JButton btnTDev6Off;
    private javax.swing.JButton btnTDev6On;
    private javax.swing.JButton btnTDev7Off;
    private javax.swing.JButton btnTDev7On;
    private javax.swing.JButton btnTDev8Off;
    private javax.swing.JButton btnTDev8On;
    private javax.swing.JButton btnTubusOff;
    private javax.swing.JButton btnTubusOn;
    public javax.swing.JCheckBox chkCheckAdmin;
    public javax.swing.JRadioButton radTDev1aNoChange;
    public javax.swing.JRadioButton radTDev1aOff;
    public javax.swing.JRadioButton radTDev1aOn;
    public javax.swing.JRadioButton radTDev1tNoChange;
    public javax.swing.JRadioButton radTDev1tOff;
    public javax.swing.JRadioButton radTDev1tOn;
    public javax.swing.JRadioButton radTDev2aNoChange;
    public javax.swing.JRadioButton radTDev2aOff;
    public javax.swing.JRadioButton radTDev2aOn;
    public javax.swing.JRadioButton radTDev2tNoChange;
    public javax.swing.JRadioButton radTDev2tOff;
    public javax.swing.JRadioButton radTDev2tOn;
    public javax.swing.JRadioButton radTDev3aNoChange;
    public javax.swing.JRadioButton radTDev3aOff;
    public javax.swing.JRadioButton radTDev3aOn;
    public javax.swing.JRadioButton radTDev3tNoChange;
    public javax.swing.JRadioButton radTDev3tOff;
    public javax.swing.JRadioButton radTDev3tOn;
    public javax.swing.JRadioButton radTDev4aNoChange;
    public javax.swing.JRadioButton radTDev4aOff;
    public javax.swing.JRadioButton radTDev4aOn;
    public javax.swing.JRadioButton radTDev4tNoChange;
    public javax.swing.JRadioButton radTDev4tOff;
    public javax.swing.JRadioButton radTDev4tOn;
    public javax.swing.JRadioButton radTDev5aNoChange;
    public javax.swing.JRadioButton radTDev5aOff;
    public javax.swing.JRadioButton radTDev5aOn;
    public javax.swing.JRadioButton radTDev5tNoChange;
    public javax.swing.JRadioButton radTDev5tOff;
    public javax.swing.JRadioButton radTDev5tOn;
    public javax.swing.JRadioButton radTDev6aNoChange;
    public javax.swing.JRadioButton radTDev6aOff;
    public javax.swing.JRadioButton radTDev6aOn;
    public javax.swing.JRadioButton radTDev6tNoChange;
    public javax.swing.JRadioButton radTDev6tOff;
    public javax.swing.JRadioButton radTDev6tOn;
    public javax.swing.JRadioButton radTDev7aNoChange;
    public javax.swing.JRadioButton radTDev7aOff;
    public javax.swing.JRadioButton radTDev7aOn;
    public javax.swing.JRadioButton radTDev7tNoChange;
    public javax.swing.JRadioButton radTDev7tOff;
    public javax.swing.JRadioButton radTDev7tOn;
    public javax.swing.JRadioButton radTDev8aNoChange;
    public javax.swing.JRadioButton radTDev8aOff;
    public javax.swing.JRadioButton radTDev8aOn;
    public javax.swing.JRadioButton radTDev8tNoChange;
    public javax.swing.JRadioButton radTDev8tOff;
    public javax.swing.JRadioButton radTDev8tOn;
    // End of variables declaration//GEN-END:variables
}
